### PR TITLE
Added cross browser compatibility, and automatic new session id grabbing

### PR DESCRIPTION
**Pull request by superboo07**
This next update should make it work with all browsers. Also I (hopefully) added the ability for it to automatically check for and grab the next session ID when steam changes it daily.

### CODE REVIEW

**Comment by JustTemmie** [comment]
an issue i still assume is present is that the login cookies tend to expire after a week or two, and currently it doesn't seem like there's any check for this as it just checks if the cookies.txt file is present. Do you want to/feel comfortable to implement this or should i do it?

**Comment by superboo07** [comment]
I haven't been able to test it, but this code should actually grab the updated cookie hopefully.

**Comment by superboo07** [comment]
> I haven't been able to test it, but this code should actually grab the updated cookie hopefully. 

It failed to grab the new cookie :/, I'll have to figure something else out.

**Comment by superboo07** [comment]
I will be attempting a new solution to fix the issue, will update in a few days since testing is difficult.

**Comment by superboo07** [comment]
This new solution should be entirely self sufficient granted they are logged into steam on their browser. It will then save the steam cookie to a cookie.txt, which it will use from then on to track if its been updated. When its updated it will replace the cookie.txt with the updated one, and repeat. 

Praying this works

**Comment by superboo07** [comment]
Unfortunately it did not work, time for more figuring out.

**Comment by superboo07** [comment]
Considering just checking if they have the steam community cookie, then opening their browser on the steam community page to refresh it and quickly closing it afterward. Hoping that won't need to be done since making that cross platform could be a bit more difficult.

**Comment by superboo07** [comment]
Still having trouble, trying more things now 🙏

**Comment by DillonB07** [comment]
Did you manage to get it working?

**Comment by superboo07** [comment]
Cross browser support was added I believe, but automatically grabbing the new session ID wasn't unfortuntely.

**Comment by JustTemmie** [comment]
if you've thrown in the towel of sorts, i'll gladly give it an attempt myself

**Comment by superboo07** [comment]
Please feel free, its likely going to be a while since I attempt again.

**Pull request closed without merging**
