### PR TITLE
Fix "config file not found" by adding abspath

### PR DESCRIPTION
**Pull request by ash2x3zb9cy**
`os.path.dirname(__file__)` can return blank, leading to the app looking for the config file at `/config.json` (i.e. in the root directory). 
See https://stackoverflow.com/a/7783326

### CODE REVIEW

**Comment by ash2x3zb9cy** [comment]
Might be a Python version thing. This change stops the app from breaking on Python 3.6 for me

**Comment by JustTemmie** [comment]
could you also change the other times dirname() is used too?
for instances such as icons.txt, games.txt, and so on

**Comment by JustTemmie** [comment]
looks like everything's functional to me, do note though the pypresence library i'm using only officially supports python3.8 and above so you might experience problems with it.

but if it works it works!

**Comment by ash2x3zb9cy** [comment]
thanks!

**Pull request merged**
