### PR TITLE
Windows startup

### PR DESCRIPTION
**Pull request by superboo07**

### CODE REVIEW

**Comment by JustTemmie** [comment]
will be testing this myself soon-ish

**Comment by JustTemmie** [comment]
okay i haven't had the time to setup a windows VM in order to actually test this, @Radiicall :pleading_face:??

**Comment by Radiicall** [comment]
> okay i haven't had the time to setup a windows VM in order to actually test this, @Radiicall :pleading_face:??

Dont have one on hand

**Comment by pparmy** [comment]
any updates?

**Comment by JustTemmie** [comment]
> any updates?

i haven't had the time to test it out yet, if you're down to try it, please do! and tell me if there's any issues

**Comment by pparmy** [comment]
> > any updates?
> 
> i haven't had the time to test it out yet, if you're down to try it, please do! and tell me if there's any issues

,, forgive my ignorance, as I'm not too familiar with github, but I think I've made a decent amount of progress. I've just come along this error when trying to run the ``main.py`` file 
image

**Comment by pparmy** [comment]
image
and here is what happens when i put ``n``

**Comment by JustTemmie** [comment]
well, the reason if fails if you do "n" is that it's just missing some code the program needed

i'm unsure why it fails when it tries to install stuff, though if you open the script in notepad, and replace all occurances of `python3` with `python` it should work?

**Comment by pparmy** [comment]
image
I'm about to lay down for a while but I will leave you with the results

**Comment by JustTemmie** [comment]
steam API key seems to be invalid, check config.json and make sure it matches your actual key
https://steamcommunity.com/dev/apikey

**Comment by pparmy** [comment]
image
it works !  !  thank you for the assistance

**Comment by JustTemmie** [comment]
and i assume it properly launches steam presence whenever you reset the device?

**Comment by pparmy** [comment]
I had an issue with it launching before discord did so there may need to be a delay/timer set for it, or at the very least a option. I assume the cmd has to stay open while in use, correct?

OOH, better idea - allow it to retry looking for a connection

**Comment by JustTemmie** [comment]
cmd has to stay open yes, i'm a bit unsure how discord handles RPC connections on windows but it should be able to retry connecting?

**Comment by pparmy** [comment]
I'll try restarting it again, I might've clicked the in the cmd pre-emptively as it already showed ``Press any key to continue`` or something similar

**Comment by pparmy** [comment]
no luck 
image
image
my discord *is* setup to launch on system restart but it doesn't for some odd reason . . ? even then cmd doesn't retry for a connection though

**Comment by pparmy** [comment]
,,  I understand it's been a hot minute since I've kept you updated but is there a chance of reviving this? I have it working still under the ``windows-run.bat`` which is just placed inside the ``steam-presence-<insert release>`` directory.  I think the only issue would be if the bat ran before discord launched locking it to a 'Press any key to continue' screen IIRC, in which case I assume there might be a way to run until it finds a connection? but I'm not really sure

**Comment by JustTemmie** [comment]
yeah sorry i didn't mean to close this, i just deleted the dev branch, the crashing before discord thing should be fixable on my end - i'm currently rewriting a lot of the code which way require modding your installer script a bit, so i'll wait to merge it until i'm done with that, should only take a couple weeks

**Comment by LunRos** [comment]
To simplify this why not change `powershell "$s=(New-Object -COM WScript.Shell).CreateShortcut('%startupLocation%\SteamRichPresence.lnk');$s.TargetPath='%CD%\windows-run.bat';$s.Save()"

to

`powershell "$s=(New-Object -COM WScript.Shell).CreateShortcut('%startupLocation%\SteamRichPresence.lnk');$s.TargetPath='%CD%\main.py';$s.Save()"`

This removes the need for two scripts and launches main.py directly.

**Comment by LunRos** [comment]
> ,, I understand it's been a hot minute since I've kept you updated but is there a chance of reviving this? I have it working still under the `windows-run.bat` which is just placed inside the `steam-presence-<insert release>` directory. I think the only issue would be if the bat ran before discord launched locking it to a 'Press any key to continue' screen IIRC, in which case I assume there might be a way to run until it finds a connection? but I'm not really sure

You could turn off Discord's auto-start then just run it manually.

**Comment by JustTemmie** [comment]
this installer will likely need updating when i finish the fabled rewrite:tm: but it's merged for now

**Pull request merged**
